# Generated by Django 5.1.4 on 2025-05-08 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_booking', '0002_location_routeprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Store as 07XXXXXXXX or +2547XXXXXXXX', max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid Safaricom number, e.g. 07XXXXXXXX or +2547XXXXXXXX', regex='^(?:07\\d{8}|\\+2547\\d{8})$')]),
        ),
    ]
